In [1]:

import pandas as pd
import numpy as np
import seaborn as sns
sns.set()
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r'/Users/sot/Downloads/laptop.csv')
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


##  QUESTION 1
-- PANDAS VERSION

In [4]:
pd.__version__

'2.1.4'

## QUESTION 2
-- How many records are in the dataset?

In [5]:
df.count()

Laptop          2160
Status          2160
Brand           2160
Model           2160
CPU             2160
RAM             2160
Storage         2160
Storage type    2118
GPU              789
Screen          2156
Touch           2160
Final Price     2160
dtype: int64

## QUESTION 3
-- How many laptop brands are presented in the dataset?


In [6]:
df['Brand'].nunique()


27

## QUESTION 4
-- How many columns in the dataset have missing values?

In [7]:
df.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

## QUESTION 5
--What's the maximum final price of Dell notebooks in the dataset?

In [8]:
df[df['Brand'] == 'Dell']['Final Price'].max()

3936.0

## QUESTION 6

In [9]:
# a. Find the median value of Screen column in the dataset.
# b. Next, calculate the most frequent value of the same Screen column.
# c. Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
# d. Now, calculate the median value of Screen once again.

In [10]:
df['Screen'].median()

15.6

In [11]:
mode = df['Screen'].mode()
mode

0    15.6
Name: Screen, dtype: float64

In [14]:
df['Screen'].fillna(mode, inplace=True)


In [15]:
df['Screen'].median()

15.6

## QUESTION 7

In [ ]:
# a. Select all the "Innjoo" laptops from the dataset.
# b. Select only columns RAM, Storage, Screen.
# c. Get the underlying NumPy array. Let's call it X.
# d. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
# e. Compute the inverse of XTX.
# f. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
# g. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# h. What's the sum of all the elements of the result?

In [20]:
# a. Select all the "Innjoo" laptops from the dataset.
innjoo_laptops = df[df['Brand'] == 'Innjoo'][['RAM', 'Storage', 'Screen']]

# c. Get the underlying NumPy array. Let's call it X.
X = innjoo_laptops.to_numpy()

X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [24]:
# d. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

XTX = np.dot(X.T, X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [29]:
 # Compute the inverse of XTX
    
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [30]:
# f. Create an array y with values [1100, 1300, 800, 900, 1000, 1100].


y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [31]:
## # g. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

w = np.dot(np.dot(XTX_inv, X.T), y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [32]:
# h. What's the sum of all the elements of the result?

np.sum(w)

91.2998806299557